plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: eslint
      releaseRules:
        - tag: Build
          release: patch

  - "@semantic-release/release-notes-generator"

  - "@semantic-release/git"

  -  - "@semantic-release/exec"
     - shell: /bin/bash
       publishCmd: "echo ${nextRelease.version} > version"


