language: minimal

services:
  - docker

before_install:
  - docker build -t python-img .
  - docker run -d --name python-boilerplate -p 127.0.0.1:80:8000 python-img
  - docker ps -a

script:
  - ls
  - sleep 30
  - docker exec -it python-boilerplate pytest
  - curl localhost:80
