language: minimal

services:
  - docker

before_install:
  - docker build -t python-img .
  - docker run -d -p 127.0.0.1:80:8000 python-img
  - docker ps -a

script:
  - ls
  - sleep 30
  - curl localhost:80
  - curl localhost:8000
